// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABvsd10vtUTbH-BchiSDnT6ToEdL0IplM',
    appId: '1:463692088434:web:8187a5fc82aaa672376eeb',
    messagingSenderId: '463692088434',
    projectId: 'joha-8389b',
    authDomain: 'joha-8389b.firebaseapp.com',
    storageBucket: 'joha-8389b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmhDY0pQ60yP0vz7-sY6ufPZJI6s3vCFM',
    appId: '1:463692088434:android:134cd3ac83435c2a376eeb',
    messagingSenderId: '463692088434',
    projectId: 'joha-8389b',
    storageBucket: 'joha-8389b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_Xn5sKZYiUrvFKlVCUm2DvHK79v9tn04',
    appId: '1:463692088434:ios:b0fcc86037c74ec9376eeb',
    messagingSenderId: '463692088434',
    projectId: 'joha-8389b',
    storageBucket: 'joha-8389b.appspot.com',
    iosBundleId: 'com.example.johaTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_Xn5sKZYiUrvFKlVCUm2DvHK79v9tn04',
    appId: '1:463692088434:ios:dbdb204619ce7de9376eeb',
    messagingSenderId: '463692088434',
    projectId: 'joha-8389b',
    storageBucket: 'joha-8389b.appspot.com',
    iosBundleId: 'com.example.johaTest.RunnerTests',
  );
}
